### ISSUE TITLE
Issue: Text Alignment problem

### ISSUE THREAD

**Issue by shashankKeshava** [shashankKeshava/Mindtree#2]
Hi 

I'm trying to align the text at bottom center of the image my solutions does not seem to be working

The CSS source is located at [App.css](src/App.js)

## Snap of the Issue
![image](https://user-images.githubusercontent.com/15323807/32137369-fed0eb0e-bc3b-11e7-8655-0825937e3498.png)

**Comment by yugoccp** [comment]
@shashankKeshava can I try this?

**Comment by psybuglite** [comment]
I think the reason you can't center it properly is that of the CSS positioning.

**Comment by shashankKeshava** [comment]
Nice job all of you, I opted the pull request with minimal CSS changes.
